DROP TABLE IF EXISTS APPARTENIR,ANNONCES,STRUCTURES,ADMINISTRATEURS,INSTRUMENTS,NIVEAUX,LIEUX,UTILISATEURS,RUBRIQUES;

CREATE TABLE RUBRIQUES(
   nomRubrique VARCHAR(50),
   PRIMARY KEY(nomRubrique)
);

CREATE TABLE UTILISATEURS(
	mail VARCHAR(50),
	motDePasse VARCHAR(50),
	PRIMARY KEY(mail)
);

CREATE TABLE LIEUX(
   codePostal VARCHAR(50),
   ville VARCHAR(50),
   PRIMARY KEY(codePostal, ville)
);

CREATE TABLE NIVEAUX(
   niveau VARCHAR(50),
   PRIMARY KEY(niveau)
);

CREATE TABLE INSTRUMENTS(
   nomInstrument VARCHAR(50),
   -- nomRubrique VARCHAR(50) NOT NULL,
   PRIMARY KEY(nomInstrument)
   -- FOREIGN KEY(nomRubrique) REFERENCES RUBRIQUES(nomRubrique)
);

CREATE TABLE ADMINISTRATEURS(
   mail VARCHAR(50),
   nom VARCHAR(50),
   prenom VARCHAR(50),
   PRIMARY KEY(mail),
   FOREIGN KEY(mail) REFERENCES UTILISATEURS(mail)
);

CREATE TABLE STRUCTURES(
   mail VARCHAR(50),
   nomRubrique VARCHAR(50),
   tel VARCHAR(50),
   siteInternet VARCHAR(50),
   adresse VARCHAR(50),
   contact VARCHAR(50),
   zoneCarte VARCHAR(50),
   codePostal VARCHAR(50) NOT NULL,
   ville VARCHAR(50) NOT NULL,
   PRIMARY KEY(mail),
   FOREIGN KEY(mail) REFERENCES UTILISATEURS(mail),
   FOREIGN KEY(codePostal, ville) REFERENCES LIEUX(codePostal, ville)
);

CREATE TABLE ANNONCES(
   idAnnonce VARCHAR(50),
   titreAnnonce VARCHAR(50),
   description VARCHAR(50),
   photo1 VARCHAR(50),
   photo2 VARCHAR(50),
   photo3 VARCHAR(50),
   nomRubrique VARCHAR(50),
   niveau VARCHAR(50),
   nomInstrument VARCHAR(50) NOT NULL,
   codePostal VARCHAR(50) NOT NULL,
   ville VARCHAR(50) NOT NULL,
   mail VARCHAR(50) NOT NULL,
   PRIMARY KEY(idAnnonce),
   FOREIGN KEY(nomInstrument) REFERENCES INSTRUMENTS(nomInstrument),
   FOREIGN KEY(niveau) REFERENCES NIVEAUX(niveau),
   FOREIGN KEY(nomRubrique) REFERENCES RUBRIQUES(nomRubrique),
   FOREIGN KEY(codePostal, ville) REFERENCES LIEUX(codePostal, ville),
   FOREIGN KEY(mail) REFERENCES STRUCTURES(mail)
);

CREATE TABLE APPARTENIR(
   mail VARCHAR(50),
   nomRubrique VARCHAR(50),
   PRIMARY KEY(mail, nomRubrique),
   FOREIGN KEY(mail) REFERENCES STRUCTURES(mail),
   FOREIGN KEY(nomRubrique) REFERENCES RUBRIQUES(nomRubrique)
);

